name: aml_registry
channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - python==3.10.4
  - pytorch==1.11.0
  - yapf==0.31.0
  - pylint==2.12.2
  - tqdm==4.64.0
  - mlflow==1.26.0
  - torchvision==0.12.0
  - tqdm==4.64.0
  - mypy==0.910
  - pip==21.1.2
  - pip:
    - types-tqdm==4.64.7.1